name: Basic Workflow

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_test_windows:
    runs-on: windows-latest
    env:
      artifact_name: parsearg_windows.zip
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
      - uses: actions/checkout@v4

      - name: Configure cmake
        shell: bash
        run: |
          cmake -S . -B build -DTEST_ENABLE=ON

      - name: Build
        shell: bash
        run: |
          cmake --build build --config ${{ matrix.build_type }} --parallel 4

      - name: Setup OpenCppCoverage and add to PATh
        if: matrix.build_type == 'Debug'
        run: |
          choco install OpenCppCoverage -y
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH

      - name: Test with coverage
        if: matrix.build_type == 'Debug'
        working-directory: ${{ github.workspace }}/build
        run: |
          OpenCppCoverage.exe --quiet --export_type cobertura:cobertura.xml --export_type html:coverage_report --cover_children --sources ${{ github.workspace }} --excluded_sources ${{ github.workspace }}\build -- ctest.exe --build-config Debug

      - name: Upload coverage report
        if: matrix.build_type == 'Debug'
        uses: actions/upload-artifact@v4
        with:
          name: coverage_report_windows
          path: |
            build/cobertura.xml
            build/coverage_report

      - name: Package
        shell: bash
        run: |
          mkdir parsearg/
          cp parsearg.hpp parsearg/
          cp '${{ github.workspace }}/build/${{ matrix.build_type }}/parsearg.lib' parsearg/
          7z a ${{ env.artifact_name }} parsearg/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows_${{ matrix.build_type }}
          path: ${{ env.artifact_name }}

  coverage_report:
    needs: build_and_test_windows
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage_report_windows

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: cobertura.xml
          badge: false
          fail_below_min: false
          format: markdown
          hide_branch_rate: true
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Show summary Coverage Report
        shell: bash
        run: |
          cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

  build_and_test_linux:
    runs-on: ubuntu-latest
    env:
      artifact_name: parsearg_linux.tgz
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
      - uses: actions/checkout@v4

      - name: Configure cmake
        shell: bash
        run: |
          cmake -S . -B build -DTEST_ENABLE=ON -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        shell: bash
        run: |
          cmake --build build --config ${{ matrix.build_type }} --parallel 4

      - name: Test
        if: matrix.build_type == 'Debug'
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: |
          ctest -C ${{ matrix.build_type }}

      - name: Package
        shell: bash
        run: |
          mkdir parsearg/
          cp parsearg.hpp parsearg/
          cp '${{ github.workspace }}/build/libparsearg.a' parsearg/
          tar czvf ${{ env.artifact_name }} parsearg/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux_${{ matrix.build_type }}
          path: ${{ env.artifact_name }}


  release:
    needs: [build_and_test_windows, build_and_test_linux]
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged == true
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          pattern: '*_Release'
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 'parsearg ${{ github.event.pull_request.title }}'
          body: ${{ github.event.pull_request.body }}
          tag_name: ${{ github.event.pull_request.title }}
          make_latest: true
          files: |
            parsearg_linux.tgz
            parsearg_windows.zip